### ISSUE TITLE
Cannot open LinkedIn

### ISSUE THREAD

**Issue by lukeguy99** [simonfrey/unshort.link#11]
When navigating to **https://www.linkedin.com/feed/** from Chrome bookmarks bar, page load fails with  the following error:
_This page isn’t working
unshort.link redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS_

The address bar shows the following URL:
**https://unshort.link/https://www.linkedin.com/signup/cold-join?session_redirect=https://www.linkedin.com/feed/**

It also doesn't work if I go to LinkedIn from Google Search (via **https://rs.linkedin.com/**). I get the same error. The address bar shows:
**https://unshort.link/https:/www.linkedin.com/home/?originalSubdomain=rs**

**Comment by simonfrey** [comment]
Will digg into it, currently I have not in-depth idea why it is not redirecting correctly

**Comment by simonfrey** [comment]
This should be solved with version 1.5. Please check it out and report if your issue is fixed

**Comment by mmoya** [comment]
Fixed for me in version 1.5.

**Comment by lukeguy99** [comment]
Still not fixed in 1.5 for me. Now the same problem happens with www.google.com, so I had to disable the extension.

**Comment by simonfrey** [comment]
Does it work if you uncheck "direct redirect" in the plugin settings?

**Comment by lukeguy99** [comment]
No, it doesn't.

This is what happens. First I get this page for manual redirect.

**You got here because you opened the short url
https://www.linkedin.com/feed/
Redirect to
https://www.linkedin.com/signup/cold-join?session_redirect=https://www.linkedin.com/feed/**

If I click on that one I get this:
**You got here because you opened the short url
https://www.linkedin.com/signup/cold-join?session_redirect=https://www.linkedin.com/feed/
Redirect to
https://www.linkedin.com/signup/cold-join?session_redirect=https://www.linkedin.com/feed/**

And it just loops from there.

**Comment by simonfrey** [comment]
I am sure you checked that, but are you using the most recent version of the plugin?
What browser and operating system you are on?

**Comment by lukeguy99** [comment]
I'm using 1.5.2 plugin on Chrome Version 79.0.3945.88 (Official Build) (64-bit) 
Windows 10 Pro 1909

**Comment by simonfrey** [comment]
Works for me as expected on either firefox or chrome
