### ISSUE TITLE
Cookie absent

### ISSUE THREAD

**Issue by mothlight** [simonfrey/unshort.link#12]
https://t.co/yaVvZrceis?amp=1 unshortened to https://conbio.onlinelibrary.wiley.com/action/cookieAbsent instead of https://conbio.onlinelibrary.wiley.com/doi/full/10.1111/conl.12694

**Comment by simonfrey** [comment]
Ah okay, so apparantly the diff matching is not high enough for that site. Wil change it so it is redirected properly in the future.
