### ISSUE TITLE
Unblock domain used not only for short links

### ISSUE THREAD

**Issue by andrewkdinh** [simonfrey/unshort.link#13]
I have a URL shortener (YOURLS) located at https://andrewkdinh.com/u/, but everything else on the website is unrelated to it. When I go to any URL with andrewkdinh.com as the domain, it is blocked by the Firefox extension because I ran unshort.link with the short link https://andrewkdinh.com/u/resume.

I'm not sure the best way to approach this, except by manually verifying that each domain is specifically meant to be used for URL shortening (like bit.ly or tinyurl.com).

**Comment by simonfrey** [comment]
Yep that I a problem I also experienced myself so far. Maybe it could be solved by removing a provider again, if the unshortened urls are the same as the input. (Thereby it would not endup in the providers endpoint and not be unshortened by the extension)

Definetly an issue with a high priority for me! If anyone has other ideas on it I would be happy to hear them.

**Comment by simonfrey** [comment]
I added the removing of hosts if they do not redirect (https://github.com/simonfrey/unshort.link/commit/c804c048604c0f517f19af28dd7400b08c8b3f9e) 

So sadly there is currently no support for a host having two functions (redirect & not redirect)

This is not a final fix, as it removes functionality. But your site is removed again from the index.

**Comment by simonfrey** [comment]
Maybe it can be solved within the browser extension, so if a request requests another page from the same host, we do not intercept it.

**Comment by simonfrey** [comment]
I think I found a propper solution for this with webextension version 1.5. Please try it when it is deployed and report back if it solved you problem

**Comment by andrewkdinh** [comment]
Works for me. Thanks!
