### ISSUE TITLE
Cannot connect with unshort.link

### ISSUE THREAD

**Issue by d8sconz** [simonfrey/unshort.link#14]
An error occured: Could not get base: Could not get original url: Get https://youtu.be/xxxxxxxxxxxx: dial tcp: lookup youtu.be on [2001:4860:4860::8888]:53: dial udp [2001:4860:4860::8888]:53: socket: too many open files

I appreciate that this is probably a server issue at unshort.link, but the inability to temporarily disable Free Link while they sort themselves out is an issue. As things are, my only option is to completely remove Free Link in order to keep browsing.

**Comment by simonfrey** [comment]
With webextension version 1.5.2 there is a toolbar button for temporary deactivating unshort.link
