### ISSUE TITLE
Interested to Contribute: Here are some points

### ISSUE THREAD

**Issue by cyantarek** [simonfrey/unshort.link#16]
I want to help on dockerizing the application.

Also, I can see, there are lots of boilerplate code here and there which will be very hard to maintain. So, it would be better to use minimalist frameworks like Echo.

Also the code structure does not seem to be planned/designed for maintaining and extensibility.

I am interested to work on these areas.

**Comment by simonfrey** [comment]
Thanks for all the offered help. I am happy for all help.

Didn't know about echo before, looks like a nice tool. Would be in favor of adding it.

I created seperate issues for your 3 ideas, so we have them better organized. Maybe I will dig into the echo framework myself to learn about it and you could help me if I do some dump mistakes there?

**Comment by cyantarek** [comment]
Sure. Just tag me in.
