### ISSUE TITLE
Use Echo Framework

### ISSUE THREAD

**Issue by simonfrey** [simonfrey/unshort.link#17]
To remove boilerplate code we should use a small framework. As stated by @cyantarek Echo (https://echo.labstack.com/guide) could be a good fit here.

**Comment by billcobbler** [comment]
I'll take a crack at this one.

**Comment by cyantarek** [comment]
@simonfrey, can you tell me what '/d/' this route mean?

**Comment by simonfrey** [comment]
`/d/` is the route for **d**isplaying the url first before redirecting. This is the standard used for the webextension. If you select direct redirect the route without the `/d/` is used.

**Comment by simonfrey** [comment]
Any updated here?

**Comment by billcobbler** [comment]
Nope, I thought @cyantarek might beat me to it and so it fell off my radar.

**Comment by cyantarek** [comment]
I was refactoring it. After going midway, the templating part looks little bit complex to me that I could not proceed and been busy with my current full time job

**Comment by simonfrey** [comment]
Shall we close this as wontfix?
