### ISSUE TITLE
Restructure code in favor for maintaining and extensibility

### ISSUE THREAD

**Issue by simonfrey** [simonfrey/unshort.link#19]
As unshort.link grew by me just starting to code it over a weekend to a project with different contributors, it would require a restructure of the project code to make it easier for others to join in with the development and also for future extensibility.

**Comment by Jakob-em** [comment]
This would also be a good opportunity to add some tests to the codebase

**Comment by simonfrey** [comment]
A clear seperation of api and template rendered frontend would be important.

**Comment by cyantarek** [comment]
Working on it :D

**Comment by cyantarek** [comment]
I want to re design the structure based on [standard project layout](https://github.com/golang-standards/project-layout), what do you guys think?

**Comment by simonfrey** [comment]
Any update here?
