### ISSUE TITLE
Graceful error handling for unreachable redirects

### ISSUE THREAD

**Issue by Jakob-em** [simonfrey/unshort.link#22]
When you currently try to open a short link to an unreachable host you get this page: 
![image](https://user-images.githubusercontent.com/26389546/72209289-04a30300-34ad-11ea-9c15-77180e31f2dc.png)

I would find it better if there would be a proper error page instead. (In the style of the normal redirect page for example)

**Comment by simonfrey** [comment]
For this issue we simply can add a template to existing error handler for it being more pretty. https://github.com/simonfrey/unshort.link/blob/master/server/handler.go#L82-L85

**Comment by simonfrey** [comment]
Fixed with https://github.com/simonfrey/unshort.link/commit/6e0166ac6921d075ea23c71182c94d6e31fd2a02
