### ISSUE TITLE
Remove hardcoded redirect to unshort.link

### ISSUE THREAD

**Issue by Jakob-em** [simonfrey/unshort.link#24]
https://github.com/simonfrey/unshort.link/blob/de135f0f5cff846357168008f4b81ac106219725/server/static/index.html#L44

When running the server locally during development you are redirected to unshort.link when trying to use the web interface. This should be changed so that always the current host will be used for the redirect

**Comment by simonfrey** [comment]
Fixed with https://github.com/simonfrey/unshort.link/commit/8235de0c8f8749a2bd196ea9f785c7f8a270e331
