### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by billcobbler** [simonfrey/unshort.link#25]
Would be nice to pick a CI platform (ie [Travis CI](https://travis-ci.org/) or [Gitlab](https://about.gitlab.com/)) and add this repo to it.

**Comment by simonfrey** [comment]
Funny that you note that. I am currently setting up github actions :)

**Comment by simonfrey** [comment]
Done :D https://github.com/simonfrey/unshort.link/runs/385941236
