### ISSUE TITLE
Post install hook with usage examples

### ISSUE THREAD

**Issue by simonfrey** [simonfrey/unshort.link#34]
Show a post install hook with example shortlinks to click on so the users can get used to how the webextension works.

**Comment by Jakob-em** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled
Could be helpful for the implementation

**Comment by simonfrey** [comment]
Added with extension version 1.5.5

**Comment by simonfrey** [comment]
Added with extension version 1.5.5
