### ISSUE TITLE
Amazon Links treated as short URLs

### ISSUE THREAD

**Issue by drod3763** [simonfrey/unshort.link#35]
Looks like all Amazon links are blocked by the extension as a short url. Clicking the link just returns you to the unshort.link page.

Example link:
https://www.amazon.com/Red-3TB-NAS-Hard-Drive/dp/B008JJLW4M

![Screen Shot 2020-01-20 at 1 56 28 PM](https://user-images.githubusercontent.com/7785716/72751205-dc0abf80-3bb6-11ea-9a3a-dc830d4d0d66.png)

**Comment by simonfrey** [comment]
Fixed by blacklisting amazon from being threatened as shortlink provider :D
