### ISSUE TITLE
Copy & Paste Ability

### ISSUE THREAD

**Issue by solariz** [simonfrey/unshort.link#36]
When the full link page is displayed it would be great to have a Copy to clipboard function or a way to select the link.

Sometimes there are still parts in the URL which you dont want to and want to remove manually before visiting the page.

**Comment by simonfrey** [comment]
Why don't you just right click on the button? Firefox offers me to copy the link location. Would be IMO the easiest solution for this problem. 

Automatic clipboard copy would also required at least a button click and JS is required for that.

Do you think copying it from the button is a solution?

**Comment by solariz** [comment]
Alternatively instead of using a JS just display the Link in a input box or text code block so user can copy parts of it if they want.

**Comment by simonfrey** [comment]
I would like to gather more input on this, as I for myself do not see the urge for this and it would clutter the interface.
Happy to implement it if there are more people wanting this though :smile:

**Comment by simonfrey** [comment]
Added with https://github.com/simonfrey/unshort.link/commit/d1f801c4af60def8674fef346fba2c45a09f7703

Long press on button displays a textare where the link can be edited and then copy-pasted
