### ISSUE TITLE
youtu.be un-shorted will contain parameter that indicates you can from shorted link

### ISSUE THREAD

**Issue by Gregyyy** [simonfrey/unshort.link#40]
An un-shorted YouTube link will still contain the feature=youtu.be parameter. That can be used by YouTube to track, if you can from a shorted link.

**Example**: [https://youtu.be/dQw4w9WgXcQ](https://youtu.be/dQw4w9WgXcQ) will return: [https://www.youtube.com/watch?v=dQw4w9WgXcQ&amp;feature=youtu.be](https://www.youtube.com/watch?v=dQw4w9WgXcQ&amp;feature=youtu.be). Expected result would be that `&amp;feature=youtu.be` is removed.

**Comment by simonfrey** [comment]
Related to #29 #32

**Comment by simonfrey** [comment]
Fixed with https://github.com/simonfrey/unshort.link/commit/81144e35561defc93bf6efbd9e1d2443d821e747 by adding the youtube parameter to the static parameter removal check
