### ISSUE TITLE
Blacklist Sources

### ISSUE THREAD

**Issue by solariz** [simonfrey/unshort.link#42]
Hey,

using unshortlink now for about a week. What I noticed is that the "Blacklist" seems a bit strict, some service links like some shops or utilities like Droplr are displayed as "Blacklisted" of course you still can click it but it is a bit confusing cause those are legit services.

What is the source of the Blacklists? Is there maybe a less strict one to only block malware sites? Or can be a whitelist overriding the blacklist added?

**Comment by simonfrey** [comment]
The blacklist source ist the "Ultimate h.o.s.t.s" list. https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist

Another less restrictive may be of use for the project, as overblocking trains the user to ignore the blacklist alert and that would be contraproductive. Do you have other lists in mind?

**Comment by solariz** [comment]
Guess the ultimate hosts file is to huge, it also contains ad blocks, p2p sites and tier 3 risks. 

Altarnative would be the malwaredomainlist which only contains domains with confirmed malware / virus or fishing.  Free for non commercial use:  http://www.malwaredomainlist.com/forums/index.php?topic=3270.0  

Another approach would be implementing a firehol ipset check in the proxy part of unshort. But this require some coding, instead of just resolving the DNS of the domain (short link AND full url) it will query a NS for the A Record and check the resulting IP against https://iplists.firehol.org/?ipset=firehol_level1

**Comment by simonfrey** [comment]
Getting the IP for the firehol should not be a big deal in go. Why do you think this would be a better solution than checking against the domain list?

**Comment by Jakob-em** [comment]
I think that using an IP list is better than relying on domains, because domains could be changed more easily/frequently.
I agree with you @simonfrey that resolving the IP address of the domain is not a problem at all. But i see more work to be done in checking against the provided IP list, as it includes whole subnets, therefore we should think of a performant implementation for the comparison of the incoming request against the firehol blacklist.

**Comment by Jakob-em** [comment]
In my opinion we should first evaluate other domain blacklists, before switching to an IP based approach.

**Comment by drod3763** [comment]
I think it should just be redirection services. Most people will use an adblocker for blacklists.

**Comment by simonfrey** [comment]
Not a fan of that option. It is a good idea, that we use a less agressive blacklist, but completly removing the blacklist feature is IMO a bad idea as it is a main fihsing application for shortlinks to trick people into opening bad urls and this should be prevented by unshort.link as well.

**Comment by drod3763** [comment]
Can we at least get an option to turn it off for those of us who don’t need to be protected in this way?

**Comment by Jakob-em** [comment]
I agree that making the blacklist feature opt out would be a good idea

**Comment by simonfrey** [comment]
Me too. Will add that to the server and the plugin on the weekend. Will be added as new route /nb (no blacklist)

**Comment by drod3763** [comment]
Who are we protecting here anyway, if you are worried about phishing, most browsers already protect you from that with the certificate warnings-at least for major sites. There are other extensions that already do this well too and most people who would install this likely installed those first.

**Comment by solariz** [comment]
Don't understand it. The unshort.link is not actually BLOCKING - if the domain is on a Blacklist it is just highlighting it and warning the user. Which is definitly a good thing, if the user is aware that it may be malware / suspicious he still can continue.

![screenshot_20200205-223303](https://user-images.githubusercontent.com/4168339/73885119-83e6e500-4867-11ea-9bbc-fbc590d1ff19.png)

I wouldn't over do it - as written in my 2nd post here a to strict blacklist like now (also blocking shortlink services in general) is confusing the user. But if a malware confirmed domain blacklist is used it is just benefits the user and there should be no reason to opt out because low to none false positive.

**Comment by drod3763** [comment]
Not always true, sometimes clicking the link just sends you back to the unshort.link page.

Also not low to none, just a few days ago it was blocking amazon.com. I prefer unix style applications-do one thing and do it well. If you need more functionality there are plenty of tools available.

As it is, I wouldnt recommend using a browser without ublock/umatrix why do i need this too?

**Comment by solariz** [comment]
Because if it is implemented just as a plain warning there is no reason not to do. Most adblock setups only contain Adblocking lists, even uBlock Origin or nano Adblock do not have a good Antifishing and Anti Malware Site enabled by default because the impact is high.

I agree that there should be no Block on anything, just a warning. And current Blocklist as written several times is not suitable for that because it just add every domain uncontrolled even Short Link services or legit sites like amazon. So a mire restrictive List without false positives and a Warning only will not do any harm.

**Comment by simonfrey** [comment]
I agree with both of you, but an opt-out is an easy feature to implement and it would solve both uses cases. If you realy do care about not being protected by unshort.link than you can deactivate it, but standard is the alert which IMO 99% of the users will keep activated. 

Other thing is still to agree on good blocklists which are not overblocking.the malerwaredomainslist.com alone seems a bit small for my taste, doesn't it?

Found the following others, we could combine with the malwaredomainlist?
- https://urlhaus.abuse.ch/
- https://isc.sans.edu/feeds/suspiciousdomains_Low.txt
- https://support.clean-mx.com/clean-mx/xregister.php

**Comment by solariz** [comment]
guess a combination of urlhaus, suspiciousdomains_low and malwaredomain list is good enough. The clean-mx mostly contain spammers not only malware.

**Comment by simonfrey** [comment]
The unshort.link website uses now urlhaus and suspicous domains (as suspicous already includes malwaredomain)

As proposed I will add the optout to the plugin and the server on the weekend.

**Comment by Jakob-em** [comment]
@simonfrey Did you test if the urlhaus list works as expected, because when i remember correctly the matching i done based on the domain and not the whole path.

**Comment by simonfrey** [comment]
Thanks for that heads up. I was to fast and did not check that. So urlhaus does not work with the current implementation.

**Comment by simonfrey** [comment]
The skip blacklist feature is implemented and will be rolled out to the extensions together with the fix for #34 as version 1.5.5 in the course of the weekend
