### ISSUE TITLE
"directly redirect" not working anymore

### ISSUE THREAD

**Issue by solariz** [simonfrey/unshort.link#46]
Just want to check if the directly redirecting feature act different on blacklist URL or normal URL. But found it is not working at all in my Firefox 73. 

Addon > Settings > Directly Redirect = checked

Clicking a Short URL e.g. https://t.co/OpD8AO5oj0?amp=1 still just see the unshort.link Info page with unshorted link.

**Comment by simonfrey** [comment]
Fixed with https://github.com/simonfrey/unshort.link/commit/599b06a169df061f7aef0bc3b45ced72184ad74f
