### ISSUE TITLE
Add support to work along side amazon smile extension

### ISSUE THREAD

**Issue by ctrlcmdshft** [simonfrey/unshort.link#47]
If clicking a link that redirects to amazon with the amazon smile plugin installed the browser link then goes into a no stop reload loop 

This is the extension https://addons.mozilla.org/en-US/firefox/addon/amazon-smile/
This is the link that reload nonstop https://amzn.to/38IvHG7

**Comment by simonfrey** [comment]
Oh, that is a hard to solve issue. As what happens is:
1) Click on amazon link
2) Smile plugin interupts and adds the referal code
3) Unshort interupts and removes the referal code back to link 1)
4) Repeat at step 2)

A workaround is to temporary deactivate unshort.link when you visit an amazon link. You can do this by clicking on the icon in the bar, it should than turn gray and not interrupt anymore. 

I will be thinking about a solution, maybe the plugin could detect if the smile plugin is installed an than redirect amazon urls or so...but I am not yet sure if that is possible with the webextension api.
Other solution would be to add an option to unshort.links config page, but would be less elgant.

**Comment by simonfrey** [comment]
Did not find a solution to make this work properly. Please temporary deactivate the plugin if you want to use the Amazon Smile one.

Maybe I will add the feature to redirect to amazon smile in the future so only unshort.link is required but no other smile plugin. Will close this one as wontfix
