### ISSUE TITLE
New site tb.cn

### ISSUE THREAD

**Issue by pixiandouban** [simonfrey/unshort.link#57]
Happy Holidays.

Would you please add a tb.cn short link, for example https://m.tb.cn/h.4TdaCIg?sm=cfbf79.

Tb.cn is a Alibaba's short link service.

By the way, I can't send a email to your email.

**Comment by simonfrey** [comment]
You can do this yourself by unshortening links on the website. When a valid shortlink is found it will automatically be added to the providers list
