### ISSUE TITLE
Create logo and adapt design to it

### ISSUE THREAD

**Issue by simonfrey** [simonfrey/unshort.link#6]
It would be nice to have a responsive (SVG) logo for the usage in the web stores (firefox & chrome) and on the site. 

Feel free to play around with ideas, but keep in mind there will be a new design of the website soon: https://i.imgur.com/dsDmG3t.png 

Try to adapt your design to it

**Comment by RaviTejaCMS** [comment]
Hey how about these?

![1](https://user-images.githubusercontent.com/13203149/72157139-30ef4e80-33dd-11ea-8f55-1dc0f5edddbc.png)

![2](https://user-images.githubusercontent.com/13203149/72157328-a8bd7900-33dd-11ea-9b0d-a54f6b0c75fc.png)


![3](https://user-images.githubusercontent.com/13203149/72157339-ae1ac380-33dd-11ea-80ee-3edd7397ebe1.png)

**Comment by simonfrey** [comment]
I really like the first one :D The colors and font of it is really nice. I would adapt the rest of the website to that color schema if we go for that one

**Comment by simonfrey** [comment]
But TBO, I don't get the padlock symbol meaning. I like how it looks though :D

**Comment by RaviTejaCMS** [comment]
I meant the padlock is kind of related to privacy and security :,-)
So any suggestions instead of Padlock?

**Comment by simonfrey** [comment]
No not really, as you state the padlock is a good idea as everyone associates it with privacy & security :D

**Comment by RaviTejaCMS** [comment]
Cool.!
Time to close the Issue.?

**Comment by simonfrey** [comment]
Could you please provide me with the color codes, the font (is it GPLv3 compatible?) and the svg of the logo?

**Comment by RaviTejaCMS** [comment]
Actually I have generated them using [this](https://looka.com) Website so I don't remember the color codes and the font style. 😬😬

**Comment by simonfrey** [comment]
I checked the page and sadly it is not compatible with open source as far as I got that. Sadly we can't use it than

**Comment by simonfrey** [comment]
But I realy do like the colors of the first image. Maybe if some else could rebuild it by hand, that he/she could use the colors :D

**Comment by simonfrey** [comment]
@carlkrg Could maybe help here with building the logo?

**Comment by RaviTejaCMS** [comment]
Background color code is 0F1E4A 
The slogans color code is FFBA51
probably [this](https://image-color.com/) website could give more info on the color codes used in that image

**Comment by Mhowser** [comment]
I think it would be a cool touch to make the slash a double slash `//` like how its used in `https://`

**Comment by roket1428** [comment]
Hey @simonfrey I'm creating logo for you. I will update after finished

**Comment by roket1428** [comment]
i recreated first logo in inkscape
Color codes: blue #030f34, yellow gradient #da892f #bbc027
Svg-link: https://drive.google.com/open?id=1-RN2Jqfac8cwVELpDY9zCKS-xbkgADye
for font you can use montserrat https://github.com/JulietaUla/Montserrat

**Comment by simonfrey** [comment]
Nice :D 
@roket1428 Would you be willing to adapt the design accordingly and open a PR for that?

**Comment by RaviTejaCMS** [comment]
@roket1428 nice one.!

**Comment by roket1428** [comment]
@simonfrey Sure but give me some time I'm busy this week.

**Comment by roket1428** [comment]
i made something like this;
![scrshot1](https://user-images.githubusercontent.com/46240987/72853557-cb477000-3cc2-11ea-88d2-a1b0916b157d.jpg)
![scrshot2](https://user-images.githubusercontent.com/46240987/72853558-cbe00680-3cc2-11ea-81f0-addf71fec61e.jpg)

Any ideas or suggestions?

**Comment by simonfrey** [comment]
I like it. Maybe if we keep all the icons in white? Less fancy, but also it focuses the attention on the input field and logo, what I would like.
