### ISSUE TITLE
Unshort.link thinks https://duckduckgo.com is a short link

### ISSUE THREAD

**Issue by ido50** [simonfrey/unshort.link#60]
For the past 2 or 3 days Unshort.link has suddenly started treating https://duckduckgo.com as a short link, redirecting it to the same URL.

Thanks.

![Screenshot_2021-01-20 Unshort link- Free link unshort service](https://user-images.githubusercontent.com/80107/105164801-7d4f8d00-5b0d-11eb-859a-363b673dc226.png)

**Comment by simonfrey** [comment]
Known and already fixed. Please restart your browser to get a updated provider list

**Comment by ido50** [comment]
Cool, thanks, works good now. Sorry if there was a duplication, didn't find anything similar in Issues.
