### ISSUE TITLE
[Suggestion] Add the lnks.gd shortener service

### ISSUE THREAD

**Issue by Cade66** [simonfrey/unshort.link#61]
The lnks.gd url shortener is resolved by checkshorturl.com, would be nice that unshort.link handle it as well.

Example (clicking is not problematic) : This [url](https://lnks.gd/l/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoxMTQ5MSwibWVzc2FnZV90eXBlIjoidXNlcl9jb25maXJtYXRpb24iLCJzdWJzY3JpYmVyX2lkIjoxNDIyNDM4MzY5LCJtZXNzYWdlX2lkIjo2ODMxOTY1ODQsInVyaSI6ImV2bzp0cmFuc2FjdGlvbmFsOmVtYWlsOmNsaWNrIiwidXJsIjoiaHR0cHM6Ly9wdWJsaWMuZ292ZGVsaXZlcnkuY29tL2FjY291bnRzL1VTREhTL3N1YnNjcmliZXIvZWRpdD9wcmVmZXJlbmNlcz10cnVlI3RhYjEifQ.ykl95aOMhl_TUu3Iz4IGgfNl5GbvyZ2Y1u917giBOvA) resolves to that [url](https://public.govdelivery.com/accounts/USDHS/subscriber/new?preferences=true)

I think lnks.gd is mainly used in U.S. government urls (Medicare and so on), not sure though what it's all about. The irony is that the shortened url is longer than its source :=)

Thanks!

**Comment by simonfrey** [comment]
Fixed (in a crappy fashion) with https://github.com/simonfrey/unshort.link/commit/d3f2442ba3e4daab26d9e8ff942a0cb1d73b1902

This would also be another case where https://github.com/simonfrey/unshort.link/issues/28 would come in handy.

For now, the lnks.gd work :D (Please try with a new url, as the old one is in the cache)

---

If you like unshort.link, [please consider supporting it](https://gum.co/unshortlink)

**Comment by Cade66** [comment]
Thanks!
