### ISSUE TITLE
Feature request: option to treat non-redirects the same as redirects

### ISSUE THREAD

**Issue by dentistformyeye** [simonfrey/unshort.link#62]
I often use unshort.link to see whether a link redirects to another page, not just to see the destination of a link that I know will redirect me. Since unshort.link immediately sends me to a site if the URL doesn't redirect, I sometimes end up connecting to a site that I otherwise wouldn't want to visit.
I'd appreciate an option, probably in the form of a checkbox, to treat non-redirecting links the same way that redirecting links are treated, i.e. unshort.link keeps me on the unshort.link/d/<URL> page and allows me to edit the URL if I want to.

**Comment by simonfrey** [comment]
Weird I never thought of this. Great idea! 
I even think this should be default behavior to not redirect pages that are the same.

**Comment by simonfrey** [comment]
Done in https://github.com/simonfrey/unshort.link/commit/502df1034ec21449bece83f5e92cc816a6b78122

**Comment by simonfrey** [comment]
And deployed on unshort.link

**Comment by simonfrey** [comment]
Please consider supporting my work on the project if you find it of value :D https://gum.co/unshortlink

**Comment by dentistformyeye** [comment]
Thanks for implementing this! Regrettably, I can't donate yet, but I appreciate that you're providing this service and that it's under a free software license.
