### ISSUE TITLE
Problem on m.youtube.com

### ISSUE THREAD

**Issue by Lehmaning** [simonfrey/unshort.link#65]
The browser extension on mobile devices sometimes will identify `m.youtube.com/watch?v=*` as shortlinks, and redirect them incorrectly to `consent.yotube.com/*`.
![deeaca73-d994-401c-8d96-566311c1f6441619306577416](https://user-images.githubusercontent.com/60032845/115975398-0fe14b80-a597-11eb-88de-01d6fe0211b1.jpg)

**Comment by simonfrey** [comment]
Added to blacklist.
