### ISSUE TITLE
Wikipedia Intern link Language open unshort.link

### ISSUE THREAD

**Issue by Getuwer** [simonfrey/unshort.link#69]
Hello everyone, this is my first time I write an issue on GitHub.
So I have the extension unshort.link who works well and is really helpful.

I'm french, so most of my time when I'm on Wikipedia I read the French page. But sometimes I want to see the English page, who is often better, especially in tech. So I click on the English page link of this page (from the French page) and it opens unshort.link because he thinks it's a short link and when I click on the yellow button, it always put me on the mobile page.
This is annoying because first it opens unshort.link for nothing (this break down the UX), then it put on mobile page who is not really good on desktop.

I found this happens too when you are from Deutsche and Russian and you go to English.
I hope you can do anything
Thank you

**Comment by simonfrey** [comment]
Added wikipedia.org & m.wikipedia.org to blacklist. Could you please restart your browser and check if it works now?

Thanks for your help!

**Comment by Getuwer** [comment]
It works fine, thank you.

**Comment by Getuwer** [comment]
Sorry but when i open an english wikipedia link from google it open unshort.link and put it on mobile wikipedia
![unshortlink_wiki_mobile](https://user-images.githubusercontent.com/52105703/124962018-6ac70280-e01e-11eb-922c-ad1e6704c3b2.png)

**Comment by simonfrey** [comment]
Should be fixed with: https://github.com/simonfrey/unshort.link/commit/fd9849a2b0676c4a4fc606b2e2a0a3cf10510dae
