### ISSUE TITLE
Reload website domain blacklist without rebuilding

### ISSUE THREAD

**Issue by simonfrey** [simonfrey/unshort.link#8]
Reload the website blacklist without the need to rebuild the service. 
Currently the blacklist gets updated only during `go generate ./...` phase.

It should be automaticaly updated every X (configurable) minutes.

**Comment by Jakob-em** [comment]
Hi, i will try implementing this issue :wave:

**Comment by Jakob-em** [comment]
Did i understand correctly that the blacklist should be periodically fetched from `https://hosts.ubuntu101.co.za/domains.list` or should it just be reloaded from the local filesystem ?

**Comment by simonfrey** [comment]
Yes it should be loaded from the domain. Even better would be if you could configure n urls from where (multiple) blackslists can be loaded. (As long as they have the format of `.../domain.list`)

**Comment by Jakob-em** [comment]
Okay sure sounds like a good idea, I will implement it in the next few days. Should they be configurable via environment variables? Because i can't see any configuration files at the moment.

**Comment by simonfrey** [comment]
If you could realize it via flags would be nice: https://github.com/simonfrey/unshort.link/blob/master/server/main.go#L18-L20

**Comment by Jakob-em** [comment]
Okay thanks for the hint

**Comment by simonfrey** [comment]
Currently there was also someone who stated on reddit, that maybe that blocklist that is currenlty used does not fit that good.
Maybe we find better ones at
https://filterlists.com/

**Comment by Jakob-em** [comment]
Okay, I'll just implement it so that its easily configurable so we can exchange it at any point later on.
Another question, how about storing the blacklisted domains in the database instead of in memory?

**Comment by simonfrey** [comment]
Not sure about storing it in the DB. 

The blacklist gets accessed a lot and thereby a direct memory access is favorable. As with the map, we have direct memory access and that should be faster for use.

Flow could be:
- Download blacklist and save it into temporary file on disks (so we can work with Streams and do not have to store the new blacklist in memory)
- Process the downloaded file and update the blacklist entries in the DB (Keep in mind that you also should remove entries that are no longer on the blacklist)
(- Load the blacklist entries from the DB into a memory cache) <= What is your take on that?

With its current 11MB of space it also should not be a problem to have it in memory.

**Comment by Jakob-em** [comment]
I agree with the proposed flow. But I don't think that doing one db query each request would lead to performance issues. I will try to use an in memory sqlite database and check the performance and if there are any issues we can discuss it again
